import Icons from "../../../../assets";

export type Person = {
  id?: string;
  employeeName?: string;
  emplyeeManager?: string;
  department?: string;
  position?: string;
  subTitle?: string;
  action?: any;
  avatar?: any;
  created_at?: string;
  updated_at?: string;
};
export const data = [
  {
    id: "#2336z",
    employeeName: "Elenora",
    emplyeeManager: "Wilkinson",
    department: "HR",
    subTitle: "Hertaland",
    position: "Hertaland",
    action: "Qatar",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#2433361k",
    employeeName: "Berneice",
    emplyeeManager: "Feil",
    department: "Design",
    subTitle: "Millcreek",
    position: "Millcreek",
    action: "Nepal",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#2545qw",
    employeeName: "Frieda",
    emplyeeManager: "Baumbach",
    department: "IT",
    subTitle: "Volkmanside",
    position: "Millcreek",
    action: "Croatia",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#2452336qwe",
    employeeName: "Zachery",
    emplyeeManager: "Brown",
    position: "Millcreek",
    department: "Development",
    subTitle: "Faychester",
    action: "Saint Pierre and Miquelon",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2424212x",
    employeeName: "Kendra",
    emplyeeManager: "Bins",
    department: "IT",
    subTitle: "New Valentin",
    position: "Millcreek",
    action: "Senegal",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2342xq",
    employeeName: "Lysanne",
    position: "Millcreek",
    emplyeeManager: "Fisher",
    department: "HR",
    subTitle: "Malachitown",
    action: "Costa Rica",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#23362hd",
    employeeName: "Garrick",
    position: "Millcreek",
    emplyeeManager: "Ryan",
    department: "Manager",
    subTitle: "East Pearl",
    action: "Cocos (Keeling) Islands",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336kh",
    employeeName: "Hollis",
    emplyeeManager: "Medhurst",
    position: "Millcreek",
    department: "Leadership",
    subTitle: "West Sienna",
    action: "Papua New Guinea",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#233613d",
    employeeName: "Arlo",
    emplyeeManager: "Buckridge",
    position: "Millcreek",
    department: "Content writer",
    subTitle: "Chino",
    action: "Congo",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336kg",
    position: "Millcreek",
    employeeName: "Rickie",
    emplyeeManager: "Auer",
    department: "Hr",
    subTitle: "Nyahfield",
    action: "Sudan",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2331376x6",
    employeeName: "Isidro",
    position: "Millcreek",
    emplyeeManager: "Larson",
    department: "Design",
    subTitle: "Fort Rosinaside",
    action: "Belize",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336asd",
    employeeName: "Bettie",
    position: "Millcreek",
    emplyeeManager: "Skiles",
    department: "IT",
    subTitle: "West Feltonchester",
    action: "Poland",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336asl",
    employeeName: "Elenora",
    position: "Millcreek",
    emplyeeManager: "Wilkinson",
    department: "HR",
    subTitle: "Hertaland",
    action: "Qatar",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#243336adp",
    employeeName: "Berneice",
    position: "Millcreek",
    emplyeeManager: "Feil",
    department: "Design",
    subTitle: "Millcreek",
    action: "Nepal",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#2545sffa",
    employeeName: "Frieda",
    emplyeeManager: "Baumbach",
    department: "IT",
    position: "Millcreek",
    subTitle: "Volkmanside",
    action: "Croatia",
    avatar: Icons.testImg1,
    created_at: "1/4/2024",
    updated_at: "1/4/2024",
  },
  {
    id: "#2452336zzs",
    employeeName: "Zachery",
    emplyeeManager: "Brown",
    department: "Development",
    position: "Millcreek",
    subTitle: "Faychester",
    action: "Saint Pierre and Miquelon",

    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#24242s2k",
    employeeName: "Kendra",
    emplyeeManager: "Bins",
    department: "IT",
    subTitle: "New Valentin",
    position: "Millcreek",
    action: "Senegal",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2342dsa",
    employeeName: "Lysanne",
    emplyeeManager: "Fisher",
    department: "HR",
    position: "Millcreek",
    subTitle: "Malachitown",
    action: "Costa Rica",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336fgh",
    employeeName: "Garrick",
    emplyeeManager: "Ryan",
    position: "Millcreek",
    department: "Manager",
    subTitle: "East Pearl",
    action: "Cocos (Keeling) Islands",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336llk",
    employeeName: "Hollis",
    position: "Millcreek",
    emplyeeManager: "Medhurst",
    department: "Leadership",
    subTitle: "West Sienna",
    action: "Papua New Guinea",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336nnm",
    position: "Millcreek",
    employeeName: "Arlo",
    emplyeeManager: "Buckridge",
    department: "Content writer",
    subTitle: "Chino",
    action: "Congo",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336gu",
    employeeName: "Rickie",
    emplyeeManager: "Auer",
    position: "Millcreek",
    department: "Hr",
    subTitle: "Nyahfield",
    action: "Sudan",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336hgr",
    employeeName: "Isidro",
    position: "Millcreek",
    emplyeeManager: "Larson",
    department: "Design",
    subTitle: "Fort Rosinaside",
    action: "Belize",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
  {
    id: "#2336qe",
    position: "Millcreek",
    employeeName: "Bettie",
    emplyeeManager: "Skiles",
    department: "IT",
    subTitle: "West Feltonchester",
    action: "Poland",
    avatar: Icons.testImg1,
    createdDate: "1/5/2025",
    dateModified: "1/5/2025",
  },
] as Person[];
